version: "3"

services:
  backend:
    build: ./app
    image: jwmann13/google-books-server:test
    container_name: google-books-backend_test
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    command: node src/server.js
    links:
      - db
    restart: always
  frontend:
    build: ./client
    image: jwmann13/google-books-client:test
    container_name: google-books-frontend_test
    ports:
      - 80:80
    links:
      - backend
    restart: always
  db:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      # Map physical volume to virtual for data persistence
      # On server could be /data/db
      # For this case we will create a Docker volume and use it instead
      # You need to run docker volume create yourproject-dbdata
      - mongodb-data-volume/:/data/db
# Add this to include data volume for mongo
# Confirm this is working later
volumes:
  ? mongodb-data-volume